In [1]:
!pip install tensorflow==2.0.0b1

     |████████████████████████████████| 87.9MB 64.5MB/s 
     |████████████████████████████████| 501kB 41.6MB/s 
     |████████████████████████████████| 3.1MB 38.3MB/s 
  Found existing installation: tensorflow 1.15.0rc3
    Uninstalling tensorflow-1.15.0rc3:
      Successfully uninstalled tensorflow-1.15.0rc3


In [5]:
import tensorflow as tf
print(tf.__version__)
import numpy as np
print(np.__version__)

2.0.0-beta1
1.16.5


This is the sequence to sequence example.

In [17]:
ds = tf.data.Dataset.range(10)
ds = ds.window(5,shift=1, drop_remainder = True)
ds = ds.flat_map(lambda w: w.batch(5))
ds = ds.map(lambda w: (w[:-1], w[1:]))         ##w is the window
ds = ds.shuffle(buffer_size = 10)
ds = ds.batch(2).prefetch(1)
for x, y in ds:
  print("x =", x.numpy())
  print("y =", y.numpy())

x = [[3 4 5 6]
 [4 5 6 7]]
y = [[4 5 6 7]
 [5 6 7 8]]
x = [[5 6 7 8]
 [1 2 3 4]]
y = [[6 7 8 9]
 [2 3 4 5]]
x = [[0 1 2 3]
 [2 3 4 5]]
y = [[1 2 3 4]
 [3 4 5 6]]


This is the sequence to vector example.

In [19]:
ds = tf.data.Dataset.range(10)
ds = ds.window(5,shift=1, drop_remainder = True)
ds = ds.flat_map(lambda w: w.batch(5))
ds = ds.map(lambda w: (w[:-1], w[-1:]))         ##w is the window
ds = ds.shuffle(buffer_size = 10)
ds = ds.batch(2).prefetch(1)
for x, y in ds:
  print("x =", x.numpy())
  print("y =", y.numpy())

x = [[1 2 3 4]
 [4 5 6 7]]
y = [[5]
 [8]]
x = [[3 4 5 6]
 [2 3 4 5]]
y = [[7]
 [6]]
x = [[5 6 7 8]
 [0 1 2 3]]
y = [[9]
 [4]]
